# Generated by Django 4.1.2 on 2022-10-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLink',
            new_name='SocialUserLink',
        ),
    ]
