# Generated by Django 4.1.2 on 2022-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_account_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
